config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :tasks do
    collection do
      post :confirm
    end
  end
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings, dependent: :destroy
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :limit, presence: true
  validates :status, presence: true
  validates :priority, presence: true

  scope :title_search,  -> (title) { where("title LIKE ?", "%#{title}%") }
  scope :status_search,  -> (status) { where(status: status)}

  enum priority: { 高: 0, 中: 1, 低: 2 }

  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  before_destroy :do_not_destroy_last_admin
  has_many :tasks, dependent: :destroy

  private
  def do_not_destroy_last_admin
    if self.admin? && User.where(admin: :true).count == 1
      throw :abort
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # before_action :set_admin, only: [:update, :show, :edit, :destroy] %i記法で記入したため不要
  before_action :set_admin, only: %i[update show edit destroy]
  before_action :check_admin
  PER = 8

  def index
    @users = User.all.order(created_at: :DESC).page(params[:page]).per(PER)
  end

  def show
    @tasks = @user.tasks.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice:"#{@user.name}を登録しました!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user.id), notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice:"ユーザーを削除しました！"
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
    end

    def set_admin
      @user = User.find(params[:id])
    end

    def check_admin
      unless current_user.admin == true
        redirect_to tasks_path, notice: "あなたは管理者ではありません"
      end
    end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_logout, only: [:new]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: "ログインしました"
    else
      flash[:notice] = 'ログインに失敗しました'
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  private

def check_logout
  if logged_in?
    redirect_to tasks_path, notice:"ログイン中です"
  end
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  PER = 6

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.order(limit: :ASC).page(params[:page]).per(PER)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :ASC).page(params[:page]).per(PER)
    else
      @tasks = current_user.tasks.order(created_at: :DESC).page(params[:page]).per(PER)
    end

    if params[:search].present?
      if params[:title].present? && params[:status].present?#渡されたパラメータがタイトルとステータス両方だった場合
        @tasks = @tasks.title_search(params[:title]).status_search(params[:status]).page(params[:page]).per(PER)
      elsif params[:title].present?#渡されたパラメータがタイトルのみだった場合
        @tasks = @tasks.title_search(params[:title]).page(params[:page]).per(PER)
      elsif params[:status].present?#渡されたパラメータがステータスのみだった場合
        @tasks = @tasks.status_search(params[:status]).page(params[:page]).per(PER)
      end
    end

     @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "タスクを作成しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"ブログを削除しました！"
  end

  def confirm
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    render :new if @task.invalid?
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :limit, :status, :priority, { label_ids: [] })
  end

  def check_login
    unless logged_in?
      flash[:notice] = "ログインしてください"
      redirect_to new_session_path
    end
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :show, :edit]
  before_action :check_logout, only: [:new]

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        render :new
      end
    end

    def edit
    end

    def update
    end

    def show
      unless @user == current_user
        redirect_to tasks_path, notice: '他の人のページへアクセス出来ません'
      end
    end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :admin)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def check_logout
      if logged_in?
        redirect_to tasks_path, notice:"ログイン中です"
      end
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
end

app/views/admin/users/edit.html.erb
<h1>ユーザ編集</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%# admin/users_controllerにformwithのデータを送る %>
<%= form_with(model:[:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin, "管理者権限" %>
  <%= f.check_box :admin %>
  <%= f.submit "編集完了" %>
<% end %>

<%= link_to "管理者画面にもどる", admin_users_path %>

app/views/admin/users/index.html.erb
<h2>管理者画面</h2>
<p><%= notice %></p>
<button type="button" class = "btn"><%= link_to 'ユーザ新規登録',new_admin_user_path %></button>
  <div class="task_table">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>名前</th>
        <th>Emailアドレス</th>
        <th>管理者権限</th>
        <th>作成日</th>
        <th>アップデート日</th>
        <th>タスク数</th>
      </tr>
    </thead>
    <tbody class="admin_row">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %> </td>
          <td><%= user.email %></td>
          <td><%= "有" if user.admin? %></td>
          <td><%= user.created_at.strftime("%Y-%m-%d%H:%M") %></td>
          <td><%= user.updated_at.strftime("%Y-%m-%d%H:%M") %></td>
          <td><%= user.tasks.count %> </td>
          <td></td>
          <td><%= link_to '詳細', admin_user_path(user.id)%></td>
          <td><%= link_to '編集', edit_admin_user_path(user.id)%></td>
          <td><%= link_to '削除', admin_user_path(user.id), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate (@users) %>

app/views/admin/users/new.html.erb
<h1>ユーザ新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件エラーがあります") %>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%# admin/users_controllerにformwithのデータを送る %>
<%= form_with(model:[:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin, "管理者権限" %>
  <%= f.check_box :admin %>
  <%= f.submit "アカウント作成" %>
<% end %>

<%= link_to "管理者画面にもどる", admin_users_path %>

app/views/admin/users/show.html.erb
<p><%= notice %></p>

<article class="col-sm-12 col-md-offset-3 col-md-6">
  <p>
    ID:<%= @user.id %>
    名前:<%=@user.name %>
  </p>
  <p>Email:<%=@user.email %></p>
  <p>管理者権限:<%= "有" if @user.admin? %></p>
  <p>作成日<%=@user.created_at.strftime("%Y-%m-%d%H:%M") %></p>
  <p>更新日:<%=@user.updated_at.strftime("%Y-%m-%d%H:%M") %></p>
  <br>
  <p>タスク一覧:</p>
  <table class="table table-condensed ">
    <tr>
      <th>タスク名</th>
      <th>詳細</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td class="task_row">
        <%= task.title %>
      </td>
      <td><%= task.content %></td>
      <% end %>
    </table>
    <p><%= paginate @tasks %></p>
    <%= link_to '編集', edit_admin_user_path(@user)%>
    <%= link_to '削除', admin_user_path(@user), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <p><%= link_to "管理者画面にもどる", admin_users_path %></p>
  </article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManyouKadai</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="header">タスク管理システム</header>
  <% if logged_in? %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <% else %>
  <%= link_to "SignUp", new_user_path %>
  <%= link_to "Login", new_session_path %>
  <% end %>
  <%= yield %>
  <footer>
    <p>運営会社yuuma株式会社</p>
    <p>© 2020-2021 Copyright yuuma Corp.</p>
  </footer>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="task_title">
    <%= form.label :limit %>
    <%= form.datetime_field :limit %>
  </div>
  <div class="task_title">
    <%= form.label :status %>
    <%= form.select :status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], include_blank: "選択して下さい" %>
  </div>
  <div class="task_title">
    <%= form.label :priority %>
    <%= form.select :priority, [["高", "高"], ["中", "中"], ["低", "低"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= form.label :label %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "一覧へ戻る", tasks_path %>

app/views/tasks/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @task, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :limit %>
  <%= form.hidden_field :status %>
  <%= form.hidden_field :priority %>
  <%= form.hidden_field :name %>
  <p>タイトル:<%= @task.title %></p>
  <p>本文:<%= @task.content %></p>
  <p>終了期限:<%= @task.limit.strftime("%Y-%m-%d%H:%M") %></p>
  <p>ステータス:<%= @task.status %></p>
  <p>優先順位:<%= @task.priority %></p>
  <p><% @task.labels.each do |label| %>
    <%= label.name %>
    <% end %>
  </p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%= notice %></p>

<article class="col-sm-12 col-md-offset-1 col-md-10">
  <div class="search">
    <%= form_with(model: @task, method: :get, url: tasks_path, local: true) do |form| %>
    <%= form.label :title_search, "タイトル検索" %>
    <%= form.text_field :title %>

    <%= form.label :status_search, "進捗検索" %>
    <%= form.select :status, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], include_blank: true, selected: '' %>

    <%= form.hidden_field :search, value: 'true' %>
    <%= form.submit "検索"%>
  </div>
  <div class="sort">
    <%= form.submit "期限順に並べる", name: 'sort_expired' %>
    <%= form.submit "優先順に並べる", name: 'sort_priority' %>
  </div>
  <div class="label_search">
    <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
    <%= form.submit 'ラベル検索', name: nil %>
  </div>
  <% end %>

  <table class="table table-striped">
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>進捗</th>
      <th>優先順位</th>
      <th>ラベル</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td class="task_row">
        <%= task.title %>
      </td>
      <td><%= task.content %></td>
      <td><%= task.limit.strftime("%Y-%m-%d%H:%M") %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td>
        <% task.labels.each do |label| %>
        <%= label.name %>
        <% end %>
      </td>
      <td><%= link_to '詳細', task_path(task.id) %></td>
      <td><%= link_to '編集', edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to '削除', task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
    <% end %>
  </table>
  <%= paginate @tasks %>
  <div class="new_task">
    <%= link_to '新しくタスクを投稿する', new_task_path %>
  </div>
</article>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タイトル: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>
<p>終了期限:<%= @task.limit.strftime("%Y-%m-%d%H:%M") %></p>
<p>進捗:<%= @task.status %></p>
<p>優先順位:<%= @task.priority %></p>
<p><% @task.labels.each do |label| %>
  <%= label.name %>
  <% end %>
</p>
<%= link_to "一覧へ戻る", tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件エラーがあります") %>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "アカウント作成" %>
<% end %>

<%= link_to "ログイン画面にもどる", new_session_path %>

app/views/users/show.html.erb
<p><%= flash[:notice] %></p>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to "タスク一覧画面へ", tasks_path %>